const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_USER_BY_KEY: 'GET_USER_BY_KEY',
    
    GET_PRODUCT_BY_KEY: 'GET_PRODUCT_BY_KEY',
    ADD_PRODUCT_TO_SHOPPING_CART: "ADD_PRODUCT_TO_SHOPPING_CART",

    ADD_PRODUCT_TO_SHOPPING_CART_SUCCESS: "ADD_PRODUCT_TO_SHOPPING_CART_SUCCESS"
    
}

export default actionTypes